In [2]:
import numpy as np


In [3]:
a = np.array([[[0,1,2],[1,0,1]],[[0,1,1],[1,0,0]]])

In [5]:
a.shape[0]

2

In [7]:
for i in range(2):
    
    print(a[i].shape)
    a[i].reshape()

[[0 1 2]
 [1 0 1]]
(2, 3)
[[0 1 1]
 [1 0 0]]
(2, 3)


In [12]:
np.reshape(a,(2,6))

array([[0, 1, 2, 1, 0, 1],
       [0, 1, 1, 1, 0, 0]])

In [14]:
b= np.prod(np.array(a[-1].shape))
print(b)

6
