In [1]:
import numpy as np


In [3]:
a = np.array([[[0,1,2],[1,0,1]],[[0,1,1],[1,0,0]]])

In [4]:
p=0.5
b=  np.random.rand(2,2)
a=  b< p # first dropout mask

print(a)
print(b)
a.shape

[[ True False]
 [False  True]]
[[0.22936476 0.58761771]
 [0.57687946 0.07751986]]


(2, 2)

In [7]:
for i in range(2):
    
    print(a[i].shape)
    a[i].reshape()

[[0 1 2]
 [1 0 1]]
(2, 3)
[[0 1 1]
 [1 0 0]]
(2, 3)


In [12]:
np.reshape(a,(2,6))

array([[0, 1, 2, 1, 0, 1],
       [0, 1, 1, 1, 0, 0]])

In [14]:
b= np.prod(np.array(a[-1].shape))
print(b)

6


In [9]:
a=[[1,2],[3,4]]
c = np.pad(a,(1),'constant', constant_values=(0))
c

array([[0, 0, 0, 0],
       [0, 1, 2, 0],
       [0, 3, 4, 0],
       [0, 0, 0, 0]])