In [1]:
import numpy as np

In [3]:
a=np.array([[2,1],[0,3]])
b=np.array([[2],[1]])
c = a.dot(b)
print(c)
print(a)

[[5]
 [3]]
[[2 1]
 [0 3]]


In [7]:
X = [[1,2],[0,3]] #2x2
X_train=[[0,0,0],[1,1,1]] #2x3
num_test = 2
num_train = 3
dists = np.zeros((num_test, num_train))
for i in range(num_test):
        dists[i,0] = np.sum((X[i,0] - X_train)**2,axis=1)
    

TypeError: list indices must be integers or slices, not tuple

In [10]:
a = np.array([1,1,1,0,0,2,2,2])
counts = np.bincount(a)
print(np.argmax(counts))

1


In [23]:
y_train = [0,2,3,0,1,2,3,2,1,0]
dists = [[1,3,6,4,5,2],[3,2,4,5,6,1],[2,4,3,5,1,6]]
k=3

In [2]:
for i in range(3):
    #closest_y = y_train[np.argsort(dists[i,:])[:k]]
    #print(closest_y)
    #print(np.argsort(dists[i,:]))
    pass
np.argsort(dists[0])

NameError: name 'dists' is not defined

In [4]:
i = [[1,2,3],[0,0,1],[3,0,2]]
y  = np.sum(i,axis=0)
x= np.sum(i,axis=1)
print(y)
print(x)
print(np.mean(y))
print(np.mean(x))

[4 2 6]
[6 1 5]
4.0
4.0
